"use client";

import {
  LineChart,
  Line,
  ResponsiveContainer,
  CartesianGrid,
  XAxis,
  Tooltip
} from "recharts";

const data = [
  { month: "Jul", forecast: 82000 },
  { month: "Aug", forecast: 91000 },
  { month: "Sep", forecast: 98000 },
  { month: "Oct", forecast: 102000 },
  { month: "Nov", forecast: 108000 },
  { month: "Dec", forecast: 115000 }
];

export default function ForecastChart() {
  return (
    <div className="bg-[#111827] border border-slate-800 rounded-2xl p-6">
      
      <div className="mb-6">
        <h2 className="text-xl font-semibold">
          AI Forecasting Engine
        </h2>

        <p className="text-slate-400 text-sm mt-1">
          Revenue prediction generated by AI models
        </p>
      </div>

      <div className="h-[320px]">
        <ResponsiveContainer width="100%" height="100%">
          
          <LineChart data={data}>
            
            <CartesianGrid
              strokeDasharray="3 3"
              stroke="#1E293B"
            />

            <XAxis
              dataKey="month"
              stroke="#94A3B8"
            />

            <Tooltip />

            <Line
              type="monotone"
              dataKey="forecast"
              stroke="#22C55E"
              strokeWidth={3}
            />
          </LineChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
}